name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # 監聽 main 分支上的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 檢出 main 分支上的代碼
      - name: Checkout code
        uses: actions/checkout@v2

      # 設置 Node.js 環境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安裝依賴項
      - name: Install dependencies
        run: npm install

      # 構建 React 應用
      - name: Build the React app
        run: npm run build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用內置 GITHUB_TOKEN 進行授權
          publish_dir: ./build  # 將 build 文件夾部署到 gh-pages 分支
